"""
October 24, 2020
Created by: Daniel Garcia Garcia, Sebastian Loaiza Correa
"""

SERVER_ADDRESS = "127.0.0.1"
PORT = 8050
BACKLOG = 5
BUFFER_SIZE = 1024 
ENCODING_FORMAT = "utf-8"
HELLO = "HELLO"
EXIT = "EXIT"
NEW_BUCKET ="NEW_BUCKET"
LIST_BUCKET = "LIST_BUCKET"
DELETE_BUCKET ="DELETE_BUCKET"
UPLOAD_FILE = "UPLOAD_FILE"
LIST_FILE = "LIST_FILE"
DOWNLOAD_FILE = "DOWNLOAD_FILE"
DELETE_FILE ="DELETE_FILE"
